version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
        name: Fetch CocoaPods specs
        command: | curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
     - run:
        name: Install cocoapods
        command: pod install --verbose
      - run:
          name: Build and test
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone XR
            SCAN_SCHEME: Geocaching_pmu
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output



workflows:
  version: 2.1
    build-and-test:
        jobs:
            -build-and-test
