# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)
platform :ios do
    lane :hello_world do
       puts("hello world")
    end
#Lint
    lane :lint do 
    sh "mkdir -p ../output"
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      mode: :lint,
      output_file: "output/swiftlint.result.json",
      config_file: ".swiftlint.yml",
      ignore_exit_status: false
    )
    end
#Tests
  lane :tests do
    run_tests(
    scheme: "Geocaching_pmu",
    include_simulator_logs: false,
    configuration: "Debug",
    code_coverage: true,
    output_directory: "output/scan",
    device: 'iPhone 11')
    coverage
  end
end
